### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kazumaban** [kazumaban/furima-31665#9]
フリマアプリの挙動確認をよろしくお願いいたします。

・フリマアプリURL【https://furima-app-31665.herokuapp.com/】
・Basic認証のIDとパスワード 【admin、2222】
・出品者用のメールアドレスとパスワード【test@123456、As123456】
・購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
【test@1234567、As123456】
・購入用カードの番号・期限・セキュリティコード
【424242424242、12月21年、123】

**Comment by MoonMaker23** [comment]
ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
頂きましたURL「https://furima-app-31665.herokuapp.com/%E3%80%91」にアクセスしました所、添付のエラー画面に遷移しました。
アプリにアクセスできるよう、修正をお願い致します。
![image](https://user-images.githubusercontent.com/69611629/100419851-b698ed00-30c8-11eb-93bf-7f38eb3c5526.png)


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kazumaban** [comment]
フリマアプリの挙動確認をよろしくお願いいたします。

・フリマアプリURL【 https://furima-app-31665.herokuapp.com/ 】
　　**※【】を読み込んで開けていませんので確認していただけますでしょうか？**
・Basic認証のIDとパスワード 【admin、2222】
・出品者用のメールアドレスとパスワード【test@123456、As123456】
・購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
【test@1234567、As123456】
・購入用カードの番号・期限・セキュリティコード
【424242424242、12月21年、123】

**Comment by oshim0115** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・ログイン時に購入済み商品に対して購入ボタンが表示されないように修正をお願いします。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kazumaban** [comment]
購入ボタンの表示分岐を修正いたしましたのでご確認よろしくお願いいたします。

・フリマアプリURL【 https://furima-app-31665.herokuapp.com/ 】
・Basic認証のIDとパスワード 【admin、2222】
・出品者用のメールアドレスとパスワード【test@123456、As123456】
・購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
【test@1234567、As123456】
・購入用カードの番号・期限・セキュリティコード
【424242424242、12月21年、123】

**Comment by sho0127** [comment]
kazumabanさん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
[記載されている購入用情報を入力して、購入しようとしたところエラーが発生しました]
カード情報など、間違えているところがないかもう一度確認しましょう！
<img width="786" alt="スクリーンショット 2020-11-30 10 32 19" src="https://user-images.githubusercontent.com/68053333/100559943-9ef37b80-32f7-11eb-959a-71ec591e1d2c.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kazumaban** [comment]
クレジットカード番号に誤りがありました。
再度ご確認よろしくお願いいたします。

・フリマアプリURL【 https://furima-app-31665.herokuapp.com/ 】
・Basic認証のIDとパスワード 【admin、2222】
・出品者用のメールアドレスとパスワード【test@123456、As123456】
・購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
【test@1234567、As123456】
・購入用カードの番号・期限・セキュリティコード
【4242424242424242、12月21年、123】

**Comment by tnk1215** [comment]
ご提出ありがとうございます‼︎
再度確認させていただきました。問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**Comment by kazumaban** [comment]
ご確認いただきありがとうございました。
